custom:
  enable_rule_generator: true
  overwrite_original_rules: true

  proxy_groups:
  - {import: "https://raw.githubusercontent.com/hardy-one/prefini/master/snippets/dler_groups.txt"}

  rulesets:
  - {import: "https://raw.githubusercontent.com/hardy-one/prefini/master/snippets/rulesets.txt"}


  # clash_rule_base: base/forcerule.yml
  # surge_rule_base: base/surge.conf
  # surfboard_rule_base: base/surfboard.conf
  # mellow_rule_base: base/mellow.conf
  # quan_rule_base: base/quan.conf
  # quanx_rule_base: base/quanx.conf

  rename_node:
  - {match: "(.*)( ->)(.*)", replace: "$1"}
  - {import: snippets/rename_node.txt}

  add_emoji: false
  remove_old_emoji: true
  # emojis:
  # - {import: snippets/emoji.txt}

  # include_remarks: []
  # exclude_remarks: []
  # template_args:
  # - {key: clash.dns.port, value: 5353}
