custom:
  enable_rule_generator: true
  overwrite_original_rules: true

  proxy_groups:
  {% if default(request.group, "") == "1" %}
  - {import: "https://raw.githubusercontent.com/hardy-one/prefini/master/snippets/simple_groups.txt"}
  {% else if default(request.relay, "") == "1" %}
  - {import: "https://raw.githubusercontent.com/hardy-one/prefini/master/snippets/dler_groups_relay.txt"}
  {% else %}
  - {import: "https://raw.githubusercontent.com/hardy-one/prefini/master/snippets/dler_groups.txt"}
  {% endif %}
  
  rulesets:
  {% if default(request.ruleset,"") == "1" %}
  - {import: "https://raw.githubusercontent.com/hardy-one/profile/master/snippets/ruleset_de.txt"}
  {% else %}
  - {import: "https://raw.githubusercontent.com/hardy-one/profile/master/snippets/ruleset_de_2.txt"}
  {% endif %}
  
  - {ruleset: "clash-ipcidr:https://raw.fastgit.org/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml", group: "DIRECT", interval: 86400}
  - {rule: "FINAL", group: "Final"}
  
  clash_rule_base: https://raw.githubusercontent.com/hardy-one/profile/master/base/clash.yaml
  surge_rule_base: https://raw.githubusercontent.com/hardy-one/profile/master/base/surge.conf

  rename_node:
#   - {match: "(.*)( -.*)( ->.*)", replace: "$1$3"}
  - {match: "(.*)( -.*)", replace: "$1"}
  - {import: snippets/rename_node.txt}

  add_emoji: false
  remove_old_emoji: false
