custom:
  enable_rule_generator: true
  overwrite_original_rules: true

  proxy_groups:
  # - {import: "https://raw.githubusercontent.com/hardy-one/prefini/master/snippets/simple.txt"}
  - {name: PROXY, type: select, rule: ["香港 CC ",  "CC", "IEPL", "BGP", ".*"]}
  - {name: NETFLIX, type: select, rule: ["[]PROXY", "香港 CC ", "CC", "IEPL", "BGP", ".*"]}
  
  rulesets:
  - {ruleset: "surge:https://raw.githubusercontent.com/hardy-one/profile/master/ruleset/Pass.list", group: "DIRECT"}
  - {ruleset: "surge:https://raw.githubusercontent.com/hardy-one/profile/master/ruleset/Fast.list", group: "NETFLIX"}
  - {ruleset: "surge:https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/Video/Netflix.list", group: "NETFLIX"}
  - {ruleset: "surge:https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list", group: "DIRECT"}
  - {ruleset: "surge:https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list", group: "PROXY"}

  - {ruleset: "clash-ipcidr:https://raw.fastgit.org/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml", group: "DIRECT", interval: 86400}  
  - {rule: "FINAL", group: "PROXY"}


  clash_rule_base: https://raw.githubusercontent.com/hardy-one/profile/master/base/clash.yaml
  surge_rule_base: https://raw.githubusercontent.com/hardy-one/profile/master/base/surge.conf

  rename_node:
  # - {match: "(.*)( -.*)( ->.*)", replace: "$1$3"}
  - {match: "(.*)( -.*)", replace: "$1"}
  - {import: snippets/rename_node.txt}

  add_emoji: true
  remove_old_emoji: true
